### PR TITLE
/pvp command

### PR DESCRIPTION
**Pull request by kurdtkobain**
removes prone/sit changes and adds /pvp command

!!untested!!

### CODE REVIEW

**Comment by Thrax989** [comment]
I test it thanks for the submit

**Comment by Thrax989** [comment]
How does this command work Im using /pvp but no such command .

**Comment by kurdtkobain** [comment]
Kk I'll have a look and fix and test then resubmit.

**Comment by kurdtkobain** [comment]
forgot to add a file sadly its a client side file so all clients would require the updated file...

**Comment by Thrax989** [comment]
if you want to package it up and get it ready we can use it if it works edit the live file and upload the live file with the tre.

**Comment by kurdtkobain** [comment]
the file that gets changed is "datatables/command/command_table.iff" does any of the current server mods change this? have not looked in the servers tre's and i don't want to use and old version if so.

**Comment by Thrax989** [comment]
I have not check in a bit id have to look myself no custom commands that im aware of have been added tot he tre but ill look in a bit .

**Comment by Thrax989** [comment]
If you want less hassle and less client /server side additions add the command to the /showpvprating It would not be hard to edit.

**Comment by Thrax989** [comment]
or you can update the live file and tre send me it and ill distribute it .

**Comment by kurdtkobain** [comment]
here's file https://mega.nz/#!aNsh2bTJ!bsVXx10VPrSo3bkJ4B8nj4-c8DvbLb7bIUmjtc2ak80 gonna run a quick test on the test box i just setup

**Comment by kurdtkobain** [comment]
server seems to segfault when creating char in my testbox

**Comment by Thrax989** [comment]
if you are using our server files need to just use the bin folder and src folder after replacing emu's you need to do /make config make clean make idl make build 

Also engine needs to match a specific point in time for it to build correctly .

Unless you are just using a clean swgemu server then you dont need to worry about this .

**Comment by kurdtkobain** [comment]
rebuilding now going for test number 2

**Comment by Thrax989** [comment]
ok sounds good I did apply your change as a test to the sit command and it worked fine =P lol although you want a new command in entirety ill wait on you for that Thanks for the hard work. You plan on doing other changes and additions or only this?

**Comment by Thrax989** [comment]
Thanks again much appreciated .

**Comment by Thrax989** [comment]
I patched it to the /showpvprating You can try for yourself works great. Let me know if you see any inconsistency's in the script thanks.

**Comment by kurdtkobain** [comment]
ok will check out, i **will** make this command work lol

**Comment by Thrax989** [comment]
good job keep at it =] We still need to make a launcher then these type of implementations would be easier on us and the community to push out new changes.

**Comment by Thrax989** [comment]
I added you to the contribution list for helping out thanks a bunch . you are right under the other Contributors that are active.

**Comment by kurdtkobain** [comment]
nice thanks did not do much really, oh and name is on there twice now lol

**Comment by Thrax989** [comment]
Alright I fixed the double name Thanks tho . Any Contribution Is Better Then No contribution Much Appreciated.

**Comment by kurdtkobain** [comment]
got it working had to change command to /setPvp and redo the iff a few time but now it works will do new pull request.

**Comment by Thrax989** [comment]
this works without the tre file?

**Comment by kurdtkobain** [comment]
no sadly still needs it, but works as intended with.

**Comment by Thrax989** [comment]
are you going to upload the new tre file along with the Live.cfg to make it a easy hot fix for people do download?

**Comment by kurdtkobain** [comment]
yup one sec getting it all zipped up, 7zip or regular zip?

**Comment by Thrax989** [comment]
regular works fine

**Comment by Thrax989** [comment]
ill re package it later with the other 11 tres people download to get on our server so it will be 12 after I get your update.

**Comment by kurdtkobain** [comment]
kk wil be in new pull request filename changed on things

**Comment by Thrax989** [comment]
No worries Thanks for all the hard work . Players will appreciate the new change.

**Comment by kurdtkobain** [comment]
np just happy i figured it out lol

**Comment by merik444** [comment]
I'm waiting for the launcher myself then I have a whole slew of things I want to try and do lol :)

**Comment by Thrax989** [comment]
Your Commit is patched and on the Live Server . here is Install Instructions For Everyone.
http://projectphoenix.com.shivtr.com/forum_threads/2534206

**Pull request merged**
