### PR TITLE
Allow crafted BE creatures to inherit area attacks from DNA.

### PR DESCRIPTION
**Pull request by bobvious**

### CODE REVIEW

**Comment by merik444** [comment]
I'll test this change on my Dev. Pretty sure last time I tried removing thsoe lines it made it so that BE pets couldn't attack at all lol

**Comment by merik444** [comment]
hmm works fine, not sure it makes any difference but it doesn't break anything

**Comment by bobvious** [comment]
If it going live on restart, I'll test it right away.   I may make my own dev server too.

This says I can delete the branch.  Should I do that?

**Comment by merik444** [comment]
it's all good. I tested it for you and it works fine. just doesn't seem to change anything lol

**Pull request merged**
