### PR TITLE
Pvp command take 2

### PR DESCRIPTION
**Pull request by kurdtkobain**
https://mega.nz/#!iEFiTDYC!sRDxKjb3wBPl_cAFongGuLCxf36H_s3p7J9DaqZrj6Q
that is the corresponding tre and swgemu_live.cfg files, the tre goes on server too in the "/home/swgemu/workspace/tre" directory

Tested working this time!

EDIT: by tested i mean i built my PVPCommand branch created char spawned on tat typed /setpvp 2 times saw the global messages got off quick test

### CODE REVIEW

**Comment by Thrax989** [comment]
We need 2 conditions to make it so FRS Jedi Cannot use this They are suppose to be Overt 24/7 and this command now allows them to go on leave and avoid being attacked  they should be red 24/7 if they are in frs.

**Comment by Thrax989** [comment]
Needs to be similar to this . They need to be excludded form using the command 	
//Check for FRS Jedi without overt
	if ((playerCreature->hasSkill("force_rank_dark_novice") || playerCreature->hasSkill("force_rank_light_novice")) && !ghost->isPrivileged()) {
		ghost->setFactionStatus(2);
	}

**Comment by kurdtkobain** [comment]
kk let me have a look

**Comment by kurdtkobain** [comment]
i think it is literaly a case of adding
`if(creature->hasSkill("force_rank_dark_novice") || creature->hasSkill("force_rank_light_novice")){
			creature->sendSystemMessage("Jedi in the FRS may not use this command.");
			return GENERALERROR;
		}`
to line 40 ish  in "MMOCoreORB\src\server\zone\objects\creature\commands\setPvp.h"

**Comment by Thrax989** [comment]
Yes my mistake If you want to do another pull request if it works ill add it unless you want me to do it .

**Comment by kurdtkobain** [comment]
naw i got it just give me a min to do git things lol

**Pull request merged**
