### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by kurdtkobain**
here you go

### CODE REVIEW

**Comment by Thrax989** [comment]
Thanks a Bunch Kamy

**Comment by kurdtkobain** [comment]
np

**Comment by kurdtkobain** [comment]
i guess i gotta work on getting a jedi so i can test stuff lol

**Comment by Thrax989** [comment]
the unlock method is open to everyone it should not take too long for you to unlock .

You plan on playing a jedi ? or you need one for testing purposes ? by the way we have a test server that noone uses lol that we all can use =P

**Comment by Thrax989** [comment]
149.56.26.152

is the test server Ip
Frog  and jedi shrine and jedi builder are there

**Comment by kurdtkobain** [comment]
not a pvp person, just like smacking things in the face with a glowbat sometimes lol , gonna add ip to my test folder thanks

**Comment by Thrax989** [comment]
if you log on let me know ill make you a admin

**Comment by kurdtkobain** [comment]
Log on the test i presume, not live?

**Comment by Thrax989** [comment]
yea test

**Comment by Thrax989** [comment]
Im on TOXIC on test

**Comment by Thrax989** [comment]
If you want to be a developer like merik who does it part time for fun I can give you a Developer Tag On the Production/Live Server no benefit other then showing off that your a developer lol =P

**Comment by kurdtkobain** [comment]
lol long as i dont get powers works for me i dont like powers on live servers kills fun

**Comment by merik444** [comment]
I felt the same way lol. Dev? Yep I enjoy it. Admin? No thanks lol

**Pull request merged**
